kind: pipeline
name: default

steps:
  - name: build
    image: plugins/docker
    settings:
      repo: claimcompass/mautic
      dockerfile: apache/Dockerfile
      context: apache
      auto_tag: true
      auto_tag_suffix: apache
    environment:
      USERNAME:
        from_secret: docker_username
      PASSWORD:
        from_secret: docker_password
