pipeline:
  build:
    image: plugins/docker
    repo: claimcompass/mautic
    dockerfile: apache/Dockerfile
    secrets: [ docker_username, docker_password ]
    auto_tag: true
    auto_tag_suffix: apache
    when:
      event: [ tag, push ]
      branch: [ master, hotfix/* ]
