kind: pipeline
name: default

steps:
  - name: build
    image: plugins/docker
    settings:
      repo: claimcompass/mautic
      dockerfile: apache/Dockerfile
      context: apache
      docker_username:
        from_secret: docker_username
      docker_password:
        from_secret: docker_password
      auto_tag: true
      auto_tag_suffix: apache

---
kind: secret

data:
  docker_username: ImTPIF1iIPRomR9HSULyhhpaJPh7ra1B_9x8f4oGW4yJP0vr9mx9MMeCAya-kA==
  docker_password: H_95E1Hli8oInHrP07Ep5D4Mm1FfuT4ibxY2ou2bJIuFMv8ISmZbAD6YndxDDSEN6Y3W_4rfHQ==
