kind: pipeline
name: default

steps:
  - name: build
    image: plugins/docker
    settings:
      repo: claimcompass/mautic
      dockerfile: apache/Dockerfile
      context: apache
      username:
        from_secret: acr_username
      password:
        from_secret: acr_password
      auto_tag: true
      auto_tag_suffix: apache
